### ISSUE TITLE
Executable Detected as Malware

### ISSUE THREAD

**Issue by SonicRay100** [MaikelChan/PDSaveEditor#2]
Works perfectly but the executable is being detected as malware:

https://www.virustotal.com/gui/file/c2f2331d24ea039f1c7327ca3f86f567e1e1c93590ca6f2fa03ace91dc4d832c

I'm using Bitdefender and it constantly moves it to quarantine.

I've submitted the file for analysis to remove the false positive, but maybe more people doing so would speed up the process.

**Comment by MaikelChan** [comment]
Hi! Thanks for reporting this. I wonder what's causing this false-positive if I can do or change something to fix it. I'll investigate the issue.

**Comment by MaikelChan** [comment]
I have uploaded a new build that fixes some small issues and seems to have reduced the amount of false-positives. Just by updating Visual Studio already generated different results on VirusTotal.

**Comment by SonicRay100** [comment]
Nice, all good on this end too :).
